app:
  name: "boilerplate"
  port: "8000"
  host: "0.0.0.0"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "postgres"
  name: "whatsapp_db"

allows:
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  origins:
    - "*"
  headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
    - "Origin"
    - "Accept"
